{{ config(materialized='view') }}


select
    flight_id,
    flight_code,
    departure_city,
    origin_airport,
    origin_country,
    departure_date,
    departure_time,
    arrival_date,
    arrival_time,
    destination_name,
    destination_airport,
    destination_country,
    flight_number,
    total_price,
    time_delta_days,
    destination_city,
    is_smallest_stops,
    duration_in_minutes,
    company_operation_type,
    marketing_company_code,
    marketing_company_name,
    operating_company_code,
    operating_company_name,
    is_self_transfer,
    is_change_allowed,
    is_cancellation_allowed,
    is_partially_changeable,
    is_partially_refundable,
    is_protected_self_transfer,
    ingestion_dt,
    'skyscanner' as channel_source,
    cast(null as varchar) as departure_airport,
    cast(null as varchar) as arrival_airport,
    cast(null as varchar) as aircraft_code,
    cast(null as integer) as number_of_stops,
    cast(null as boolean) as blacklisted_in_eu,
    cast(null as varchar) as departure_terminal,
    cast(null as varchar) as currency

from {{ ref('stg_skyscanner_flights') }}