version: 2

sources:
  - name: sources
    description: "Tablas de origen en Athena"
    database: awsdatacatalog
    schema: default
    tables:
      - name: src_skyscanner_flights
        identifier: skyscanner_staging_flights
        description: "Datos originales de Skyscanner"
      - name: src_amadeus_flights
        identifier: amadeus_staging_flights
        description: "Datos originales de Amadeus"
      - name: src_delayed_predictions_flights
        identifier: amadeus_stg_flight_delays
        description: "Datos de predicción de retrasos"
