{{ config(materialized='table') }}

select distinct
	concat(marketing_company_code, flight_number, '-' , date_format(date_parse(departure_time, '%Y-%m-%dT%H:%i:%s'), '%Y%m%d-%H%i')) as flight_id,
	concat(marketing_company_code, flight_number) as flight_code,
	origin_city as departure_city, 
	origin_airport as origin_airport_code,
	origin_country,
	date_format(date_parse(departure_time, '%Y-%m-%dT%H:%i:%s'), '%Y-%m-%d') as departure_date,
	date_format(date_parse(departure_time, '%Y-%m-%dT%H:%i:%s'), '%H:%i:%s') as departure_time,
	date_format(date_parse(arrival_time, '%Y-%m-%dT%H:%i:%s'), '%Y-%m-%d') as arrival_date,
	date_format(date_parse(arrival_time, '%Y-%m-%dT%H:%i:%s'), '%H:%i:%s') as arrival_time,
	destination_name,
	destination_airport as destination_airport_code,
	destination_country,
	flight_number,
	price_raw as price_amount,
	time_delta_days,
	destination_city,
	is_smallest_stops,
	duration_in_minutes as duration_minutes,
	company_operation_type,
	marketing_company_code as marketing_carrier_code,
	marketing_company_name,
	operating_company_code as operating_carrier_code,
	operating_company_name,
	"isSelfTransfer" as is_self_transfer,
	"isChangeAllowed" as is_change_allowed,
	"isCancellationAllowed" as is_cancellation_allowed,
	"isPartiallyChangeable" as is_partially_changeable,
	"isPartiallyRefundable" as is_partially_refundable,
	"isProtectedSelfTransfer" as is_protected_self_transfer,
	"ingestion_dt" as ingestion_timestamp
from {{ source('sources', 'src_skyscanner_flights') }}